<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Invalid Trailing Whitespace</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.trailing-whitespace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s+)$</string>
			<key>name</key>
			<string>source.invalid.trailing-whitespace</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.whitespace</string>
	<key>uuid</key>
	<string>1426910F-A8AC-4879-8289-92C028600E8F</string>
</dict>
</plist>
